Document: package
Title: Debian package Manual
Author: <insert document author here>
Abstract: This manual describes what package is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/package/package.sgml.gz

Format: postscript
Files: /usr/share/doc/package/package.ps.gz

Format: text
Files: /usr/share/doc/package/package.text.gz

Format: HTML
Index: /usr/share/doc/package/html/index.html
Files: /usr/share/doc/package/html/*.html
